spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/big_event
    username: root
    password: 123456

  data:
    redis:
      port: 6379
      host: 192.168.1.106
      password: 123456
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 1
          time-between-eviction-runs: 10s

logging:
  level:
    org.mybatis: debug

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    jdbc-type-for-null: NULL
    map-underscore-to-camel-case: true #开启驼峰命名和下划线命名的自动转换
    database-id: mysql

